### ISSUE TITLE
Unable to discover zhimi.humidifier.cb1

### ISSUE THREAD

**Issue by Evil-Crab** [syssi/xiaomi_airpurifier#142] opened 2021-01-30 14:44 UTC
For some reason, this integration is unable to connect to the humidifier.

I can ping it and miiocli on my machine works fine with it:
```
evil_crab@EvilPC:~$ miiocli airhumidifiercb1 --ip 10.10.10.202 --token dec9b..... info
Model: zhimi.humidifier.cb1
Hardware version: MTK7697
Firmware version: 1.6.7
evil_crab@EvilPC:~$ miiocli airhumidifiercb1 --ip 10.10.10.202 --token dec9b.... status
Power: on
Mode: OperationMode.High
Temperature: 23.5 °C
Humidity: 40 %
LED brightness: LedBrightness.Bright
Buzzer: True
Child lock: False
Target humidity: 70 %
Trans level: None
Speed: 996
Depth: 125
Dry: True
Use time: 830
Hardware version: 0001
Button pressed: None
```

Home assistant logs:
```
2021-01-30 15:37:11 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-30 15:37:13 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-30 15:37:13 INFO (MainThread) [custom_components.xiaomi_miio_airpurifier.fan] Initializing with host 10.10.10.202 (token dec9b...)
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.protocol] Unable to decrypt, returning raw bytes: b''
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x05\xc08\x82`\x15o\x19' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('05c03882')
            ts = 2021-01-30 14:37:13
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] Discovered 05c03882 with ts: 2021-01-30 14:37:13, token: b'ffffffffffffffffffffffffffffffff'
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 1, 'method': 'get_status', 'params': []}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:13, id: 1) << {'result': [{'msg_ver': 3, 'msg_seq': 2276, 'state': 8, 'battery': 100, 'clean_time': 2, 'clean_area': 0, 'error_code': 0, 'map_present': 1, 'in_cleaning': 0, 'in_returning': 0, 'in_fresh_state': 1, 'lab_status': 1, 'water_box_status': 0, 'fan_power': 104, 'dnd_enabled': 0, 'map_status': 3, 'lock_status': 0}], 'id': 1}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 2, 'method': 'miIO.info', 'params': []}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:13, id: 2) << {'partner_id': '', 'id': 2, 'code': 0, 'message': 'ok', 'result': {'hw_ver': 'Linux', 'fw_ver': '3.5.8_002020', 'ap': {'ssid': 'EvilNet', 'bssid': '00:11:32:7C:9C:12', 'rssi': -57}, 'netif': {'localIp': '10.10.10.201', 'mask': '255.255.255.0', 'gw': '10.10.10.1'}, 'model': 'roborock.vacuum.s5', 'mac': '7C:49:EB:9B:6A:A3', 'token': '46344a616d45457a517066356b426852', 'life': 45120}}
2021-01-30 15:37:14 INFO (SyncWorker_1) [miio.vacuum] model: roborock.vacuum.s5
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.vacuum] Using new fanspeed mapping <enum 'FanspeedV2'> for roborock.vacuum.s5
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 3, 'method': 'get_consumable', 'params': []}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:13, id: 3) << {'result': [{'main_brush_work_time': 118855, 'side_brush_work_time': 118855, 'filter_work_time': 118855, 'filter_element_work_time': 0, 'sensor_dirty_time': 118513}], 'id': 3}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 4, 'method': 'get_clean_summary', 'params': []}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:13, id: 4) << {'result': [118513, 1786942500, 92, [1612014950, 1611161325, 1611161173, 1611160406, 1611160011, 1611155709, 1611153548, 1611153264, 1611107538, 1611103299, 1611101925, 1611101822, 1611100432, 1611097905]], 'id': 4}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 5, 'method': 'get_clean_summary', 'params': []}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:13, id: 5) << {'result': [118513, 1786942500, 92, [1612014950, 1611161325, 1611161173, 1611160406, 1611160011, 1611155709, 1611153548, 1611153264, 1611107538, 1611103299, 1611101925, 1611101822, 1611100432, 1611097905]], 'id': 5}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 6, 'method': 'get_clean_record', 'params': [1612014950]}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:14, id: 6) << {'result': [], 'id': 6}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 7, 'method': 'get_dnd_timer', 'params': []}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:14, id: 7) << {'result': [{'start_hour': 22, 'start_minute': 0, 'end_hour': 8, 'end_minute': 0, 'enabled': 1}], 'id': 7}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 8, 'method': 'get_timezone', 'params': []}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:14, id: 8) << {'result': ['Europe/Amsterdam'], 'id': 8}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 9, 'method': 'get_timer', 'params': ['']}
2021-01-30 15:37:14 DEBUG (SyncWorker_1) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:14, id: 9) << {'result': [], 'id': 9}
2021-01-30 15:37:19 DEBUG (SyncWorker_2) [miio.miioprotocol] Unable to discover a device at address 10.10.10.202
2021-01-30 15:37:19 ERROR (MainThread) [custom_components.xiaomi_miio_airpurifier.fan] Got exception while fetching the state: Unable to discover the device 10.10.10.202
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 10, 'method': 'get_status', 'params': []}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:34, id: 10) << {'result': [{'msg_ver': 3, 'msg_seq': 2277, 'state': 8, 'battery': 100, 'clean_time': 2, 'clean_area': 0, 'error_code': 0, 'map_present': 1, 'in_cleaning': 0, 'in_returning': 0, 'in_fresh_state': 1, 'lab_status': 1, 'water_box_status': 0, 'fan_power': 104, 'dnd_enabled': 0, 'map_status': 3, 'lock_status': 0}], 'id': 10}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 11, 'method': 'get_consumable', 'params': []}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:34, id: 11) << {'result': [{'main_brush_work_time': 118855, 'side_brush_work_time': 118855, 'filter_work_time': 118855, 'filter_element_work_time': 0, 'sensor_dirty_time': 118513}], 'id': 11}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 12, 'method': 'get_clean_summary', 'params': []}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:34, id: 12) << {'result': [118513, 1786942500, 92, [1612014950, 1611161325, 1611161173, 1611160406, 1611160011, 1611155709, 1611153548, 1611153264, 1611107538, 1611103299, 1611101925, 1611101822, 1611100432, 1611097905]], 'id': 12}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 13, 'method': 'get_clean_summary', 'params': []}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:34, id: 13) << {'result': [118513, 1786942500, 92, [1612014950, 1611161325, 1611161173, 1611160406, 1611160011, 1611155709, 1611153548, 1611153264, 1611107538, 1611103299, 1611101925, 1611101822, 1611100432, 1611097905]], 'id': 13}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 14, 'method': 'get_clean_record', 'params': [1612014950]}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:34, id: 14) << {'result': [], 'id': 14}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 15, 'method': 'get_dnd_timer', 'params': []}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:34, id: 15) << {'result': [{'start_hour': 22, 'start_minute': 0, 'end_hour': 8, 'end_minute': 0, 'enabled': 1}], 'id': 15}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 16, 'method': 'get_timezone', 'params': []}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:34, id: 16) << {'result': ['Europe/Amsterdam'], 'id': 16}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 >>: {'id': 17, 'method': 'get_timer', 'params': ['']}
2021-01-30 15:37:34 DEBUG (SyncWorker_2) [miio.miioprotocol] 10.10.10.201:54321 (ts: 2021-01-30 14:37:34, id: 17) << {'result': [], 'id': 17}
2021-01-30 15:37:54 DEBUG (SyncWorker_1) [miio.miioprotocol] Unable to discover a device at address 10.10.10.202
2021-01-30 15:37:54 ERROR (MainThread) [custom_components.xiaomi_miio_airpurifier.fan] Got exception while fetching the state: Unable to discover the device 10.10.10.202
```

**Comment by syssi** [comment] 2021-01-30 14:51
Could you provide your HA configuration incl. the first 5 chars of your token?

**Comment by Evil-Crab** [comment] 2021-01-30 15:10
I run some additional tests on the home assistant docker:

```
➜  ~ docker ps                                                 
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
1a15c1603ac8        local/amd64-addon-vacuum_camera_server:1          "/init /run.sh"          2 minutes ago       Up 2 minutes        0.0.0.0:3000->3000/tcp                                               addon_local_vacuum_camera_server
6ae32c3689c9        dwelch2101/zigbee2mqtt-amd64:1.17.0.1             "/init ./run.sh"         2 minutes ago       Up 2 minutes        0.0.0.0:8485->8485/tcp                                               addon_7ad98f9c_zigbee2mqtt
d2461b78da9f        hassioaddons/node-red-amd64:7.2.11                "/init"                  2 minutes ago       Up 2 minutes                                                                             addon_a0d7b954_nodered
7e6c9bec1910        hassioaddons/ssh-amd64:7.8.0                      "/init"                  2 minutes ago       Up 2 minutes                                                                             addon_a0d7b954_ssh
9c90f8e12f1c        ghcr.io/hassio-addons/vscode/amd64:3.0.0          "/init"                  2 minutes ago       Up 2 minutes                                                                             addon_a0d7b954_vscode
f986b5b96912        homeassistant/amd64-addon-mosquitto:5.1           "/run.sh"                2 minutes ago       Up 2 minutes        0.0.0.0:1883-1884->1883-1884/tcp, 0.0.0.0:8883-8884->8883-8884/tcp   addon_core_mosquitto
3c5d02b5f307        homeassistant/amd64-hassio-multicast:3            "/init"                  2 minutes ago       Up 2 minutes                                                                             hassio_multicast
f54bc1965d60        homeassistant/amd64-hassio-cli:2020.11.1          "/init /bin/bash -c …"   2 minutes ago       Up 2 minutes                                                                             hassio_cli
eb1b099cd1fc        homeassistant/amd64-hassio-audio:17               "/init"                  2 minutes ago       Up 2 minutes                                                                             hassio_audio
b8ae869100e6        homeassistant/amd64-hassio-dns:2020.12.0          "/init"                  2 minutes ago       Up 2 minutes                                                                             hassio_dns
a2e2edba0f28        homeassistant/qemux86-64-homeassistant:2021.1.5   "/init"                  28 minutes ago      Up 2 minutes                                                                             homeassistant
741d1ecfba00        homeassistant/amd64-hassio-supervisor:latest      "/init"                  5 days ago          Up 2 minutes                                                                             hassio_supervisor
1e5636c18039        homeassistant/amd64-hassio-observer:2020.10.1     "/init"                  11 days ago         Up 3 minutes        0.0.0.0:4357->80/tcp                                                 hassio_observer
➜  ~ docker exec -it a2e2edba0f28 bash                                               
bash-5.0# python3
Python 3.8.7 (default, Jan  1 2021, 22:51:10) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from miio import Device
>>> miio_device = Device('10.10.10.202', 'dec9b...')
>>> miio_device.info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 177, in info
    return DeviceInfo(self.send("miIO.info"))
  File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 143, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 160, in send
    self.send_handshake()
  File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 87, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 10.10.10.202
>>> miio_device = Device('10.10.10.201', '46344...')
>>> miio_device.info()
roborock.vacuum.s5 v3.5.8_002020 (7C:49:EB:9B:6A:A3) @ 10.10.10.201 - token: 46344...
>>> exit()
bash-5.0# ping 10.10.10.201
PING 10.10.10.201 (10.10.10.201): 56 data bytes
64 bytes from 10.10.10.201: seq=0 ttl=63 time=3.635 ms
64 bytes from 10.10.10.201: seq=1 ttl=63 time=2.839 ms
^C
--- 10.10.10.201 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 2.839/3.237/3.635 ms
bash-5.0# ping 10.10.10.202
PING 10.10.10.202 (10.10.10.202): 56 data bytes
64 bytes from 10.10.10.202: seq=0 ttl=254 time=52.357 ms
64 bytes from 10.10.10.202: seq=1 ttl=254 time=12.968 ms
64 bytes from 10.10.10.202: seq=2 ttl=254 time=3.780 ms
^C
--- 10.10.10.202 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 3.780/23.035/52.357 ms
```

**Comment by Evil-Crab** [comment] 2021-01-30 15:11
> Could you provide your HA configuration incl. the first 5 chars of your token?

```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Humidifier
    host: 10.10.10.202
    token: dec9b...
    model: zhimi.humidifier.cb1
```

**Comment by syssi** [comment] 2021-01-30 15:18
Thanks for the additional testing! You could the

```
miiocli airhumidifiercb1 --ip 10.10.10.202 --token dec9b.... status
```

from your docker container too? If `miiocli` is working the HA component should be able to discover the device, too.

**Comment by Evil-Crab** [comment] 2021-01-30 15:23
No luck, miiocli can't connect to the humidifier from the HA docker. Works fine for vacuum and from my machine though.

```
➜  ~ docker exec -it a2e2edba0f28 bash
bash-5.0# miiocli airhumidifiercb1 --ip 10.10.10.202 --token dec9bfc0f372219c9498c6d63d558c2f status
Error: Unable to discover the device 10.10.10.202
bash-5.0# miiocli vacuum --ip 10.10.10.201 --token 46344a616d45457a517066356b426852 status
Running command status
<VacuumStatus state=Charging, error=No error bat=100%, fan=104% cleaned 0.0 m² in 0:00:02>
```

**Comment by Evil-Crab** [comment] 2021-01-30 15:31
I think it might be related to https://python-miio.readthedocs.io/en/latest/troubleshooting.html#discover-devices-across-subnets

**Comment by syssi** [comment] 2021-01-30 15:55
Lives your HA instance in another subnet? In this case you've identified the root cause.

**Comment by Evil-Crab** [comment] 2021-01-30 16:19
Yep, I was able to fix it by reconfiguring NAT on my router, works great now

**Comment by syssi** [comment] 2021-01-30 17:32
Perfect! I will close the issue now.

**Closed by syssi** 2021-01-30 17:32 UTC
