### ISSUE TITLE
Unsupported device found! data: zhimi.airp.mb5a

### ISSUE THREAD

**Issue by majungman** [syssi/xiaomi_airpurifier#326] opened 2023-02-17 08:07 UTC
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:129
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 16:05:40 (1 occurrences)
Last logged: 16:05:40

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.airp.mb5a

**Comment by antsmartti** [comment] 2023-03-16 10:38
Came here to create same issue, will not create duplicate.

**Comment by syssi** [comment] 2023-03-16 10:49
Duplicate of #301.

**Closed by syssi** 2023-03-16 10:49 UTC
