### ISSUE TITLE
Support Humidifier/Dehumidifiers at homekit

### ISSUE THREAD

**Issue by anhnvme** [syssi/xiaomi_airpurifier#116] opened 2020-12-04 02:42 UTC
Hello,

I'm heard that Home Assistant will be support Humidifier/Dehumidifiers with homekit.
So if you have free time, please convert few device to that Device type. 
Current Dehumidifier show as Air Conditional and humidifier show as a fan at homekit

Air Humidifier | zhimi.humidifier.v1 |   |  
-- | -- | -- | --
Air Humidifier | zhimi.humidifier.v1 |   |  
Air Humidifier CA1 | zhimi.humidifier.ca1 |   |  
Smartmi Humidifier Evaporator 2 | zhimi.humidifier.ca4 | CJXJSQ04ZM |  
Air Humidifier CB1 | zhimi.humidifier.cb1 |   |  
Mijia Smart Sterilization Humidifier S | deerma.humidifier.mjjsq | MJJSQ03DY | 4.5L, <=39dB, 450mL/h, 40W
Mijia Intelligent Sterilization Humidifier (EU version?) | deerma.humidifier.jsq | ZNJSQ01DEM | 4.5L, <=38dB, 300mL/h, 24W
Mijia Intelligent Sterilization Humidifier SCK0A45 | deerma.humidifier.jsq1 | SCKOA45, SCK0A45 | 4.5L, <=38dB, 300mL/h, 25W
Zero Fog Humidifier | shuii.humidifier.jsq001 |   |  
New Widetech Internet Dehumidifier | nwt.derh.wdh318efw1 | WDH318EFW1 | 2.7L tank, 38dB, 18L/d, 240W

- 

For more information:
- https://rc.home-assistant.io/blog/2020/12/02/release-10/
-  https://rc.home-assistant.io/integrations/homekit_controller/

Thanks you so much

**Comment by syssi** [comment] 2020-12-05 08:11
Duplicate of #115.

**Closed by syssi** 2020-12-05 08:11 UTC
