### ISSUE TITLE
Add deerma.humidifier.jsq3 support

### ISSUE THREAD

**Issue by jacob2826** [syssi/xiaomi_airpurifier#149] opened 2021-02-17 06:14 UTC
Model: deerma.humidifier.jsq3
Hardware version: RTL8720C
Firmware version: 2.0.3

**Comment by Xaxolhd** [comment] 2021-03-28 07:14
+++++++ deerma.humidifier.jsq3

**Comment by syssi** [comment] 2021-04-10 13:12
Duplicate of #123.

**Closed by syssi** 2021-04-10 13:12 UTC
