### ISSUE TITLE
deerma.humidifier.jsqm

### ISSUE THREAD

**Issue by alekst800** [syssi/xiaomi_airpurifier#234] opened 2021-11-29 20:25 UTC
Please add support "deerma.humidifier.jsqm"

**Comment by Gastello007** [comment] 2021-12-08 12:54
**Device information:**

  - Name(s) of the device : Mijia Smart Sterilization Humidifier
  - [Link:](url:https://home.mi.com/baike/index.html#/detail?model=deerma.humidifier.jsqm)

Use `miiocli device --ip <ip address> --token <token>`.

Model: deerma.humidifier.jsqm
Hardware version: esp8266
Firmware version: 2.1.3


**Additional context**
```yaml

deerma.humidifier.jsqm

2021-12-08 15:36:34 -> {"id":8741,"method":"get_properties","params":[{"did":"409742629","siid":2,"piid":5},{"did":"409742629","siid":3,"piid":1},{"did":"409742629","siid":2,"piid":6},{"did":"409742629","siid":6,"piid":1},{"did":"409742629","siid":2,"piid":1},{"did":"409742629","siid":3,"piid":7},{"did":"409742629","siid":5,"piid":1},{"did":"409742629","siid":7,"piid":1},{"did":"409742629","siid":7,"piid":2}]}
2021-12-08 15:36:34 <- {"code":0,"exe_time":250,"id":8741,"otlocalts":1638966995470923,"result":[{"code":0,"did":"409742629","piid":5,"siid":2,"value":3},{"code":0,"did":"409742629","piid":1,"siid":3,"value":47},{"code":0,"did":"409742629","piid":6,"siid":2,"value":60},{"code":0,"did":"409742629","piid":1,"siid":6,"value":true},{"code":0,"did":"409742629","piid":1,"siid":2,"value":true},{"code":0,"did":"409742629","piid":7,"siid":3,"value":26},{"code":0,"did":"409742629","piid":1,"siid":5,"value":false},{"code":0,"did":"409742629","piid":1,"siid":7,"value":false},{"code":0,"did":"409742629","piid":2,"siid":7,"value":false}]}
2021-12-08 15:36:37 -> {"params":[{"did":"409742629","siid":2,"piid":5,"value":4}]} /miotspec/prop/set
2021-12-08 15:36:37 <- {"code":0,"message":"","result":[{"did":"409742629","siid":2,"piid":5,"code":0,"exe_time":0}]}
2021-12-08 15:36:37 -> {"params":[{"did":"409742629","siid":2,"piid":6,"value":40}]} /miotspec/prop/set
2021-12-08 15:36:37 <- {"code":0,"message":"","result":[{"did":"409742629","siid":2,"piid":6,"code":0,"exe_time":0}]}
2021-12-08 15:36:39 -> {"params":[{"did":"409742629","siid":2,"piid":5,"value":3}]} /miotspec/prop/set
2021-12-08 15:36:39 <- {"code":0,"message":"","result":[{"did":"409742629","siid":2,"piid":5,"code":0,"exe_time":0}]}
2021-12-08 15:36:40 -> {"params":[{"did":"409742629","siid":2,"piid":5,"value":2}]} /miotspec/prop/set
2021-12-08 15:36:40 <- {"code":0,"message":"","result":[{"did":"409742629","siid":2,"piid":5,"code":0,"exe_time":0}]}
2021-12-08 15:36:41 -> {"params":[{"did":"409742629","siid":2,"piid":5,"value":1}]} /miotspec/prop/set
2021-12-08 15:36:41 <- {"code":0,"message":"","result":[{"did":"409742629","siid":2,"piid":5,"code":0,"exe_time":0}]}
2021-12-08 15:36:44 -> {"params":[{"did":"409742629","siid":6,"piid":1,"value":false}]} /miotspec/prop/set
2021-12-08 15:36:44 <- {"code":0,"message":"","result":[{"did":"409742629","siid":6,"piid":1,"code":0,"exe_time":0}]}
2021-12-08 15:36:45 -> {"params":[{"did":"409742629","siid":6,"piid":1,"value":true}]} /miotspec/prop/set
2021-12-08 15:36:45 <- {"code":0,"message":"","result":[{"did":"409742629","siid":6,"piid":1,"code":0,"exe_time":0}]}
2021-12-08 15:36:46 -> {"params":[{"did":"409742629","siid":5,"piid":1,"value":true}]} /miotspec/prop/set
2021-12-08 15:36:46 <- {"code":0,"message":"","result":[{"did":"409742629","siid":5,"piid":1,"code":0,"exe_time":0}]}
2021-12-08 15:36:47 -> {"params":[{"did":"409742629","siid":5,"piid":1,"value":false}]} /miotspec/prop/set
2021-12-08 15:36:47 <- {"code":0,"message":"","result":[{"did":"409742629","siid":5,"piid":1,"code":0,"exe_time":0}]}
2021-12-08 15:36:49 -> {"params":[{"did":"409742629","siid":2,"piid":1,"value":false}]} /miotspec/prop/set
2021-12-08 15:36:49 <- {"code":0,"message":"","result":[{"did":"409742629","siid":2,"piid":1,"code":0,"exe_time":0}]}
2021-12-08 15:36:51 -> {"params":[{"did":"409742629","siid":2,"piid":1,"value":true}]} /miotspec/prop/set
2021-12-08 15:36:51 <- {"code":0,"message":"","result":[{"did":"409742629","siid":2,"piid":1,"code":0,"exe_time":0}]}
2021-12-08 15:36:54 -> {"params":[{"did":"409742629","siid":2,"piid":5,"value":3}]} /miotspec/prop/set
2021-12-08 15:36:54 <- {"code":0,"message":"","result":[{"did":"409742629","siid":2,"piid":5,"code":0,"exe_time":0}]}```

**Comment by syssi** [comment] 2021-12-18 19:09
Duplicate of #216.

**Closed by syssi** 2021-12-18 19:09 UTC
