### ISSUE TITLE
Problem with homekit

### ISSUE THREAD

**Issue by rengaboy** [syssi/xiaomi_airpurifier#33] opened 2019-03-04 21:47 UTC
Hello.
I added zhimi.humidifier.ca1, all works great, but i have strange errors in my log.
`2019-03-04 21:38:52 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/homekit/type_fans.py", line 132, in update_state
    hk_speed_value = self.speed_mapping.speed_to_homekit(speed)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/homekit/util.py", line 150, in speed_to_homekit
    speed_range = self.speed_ranges[speed]
KeyError: 864
`

**Comment by rengaboy** [comment] 2019-03-04 22:41
I guess that homeassistant could not accept a speed attribute more than 100

**Comment by syssi** [comment] 2019-03-05 06:58
The different speeds of the component and alex/google/homekit doesn't align/match. That's the cause for the incompatibility. I don't know how to fix it. In my opinion the voice assistances needs a more flexible API.

**Comment by rengaboy** [comment] 2019-03-05 07:24
What is the maximum/minimum int value of speed? Maybe we could divide int value by 100? Something like that:
‘speed = (speed / 100) if speed > 1 else speed’

**Comment by rengaboy** [comment] 2019-03-05 17:36
I wonder, for what purpose do we need to  forward int speed value to HomeAssistant?

**Comment by rengaboy** [comment] 2019-03-05 18:29
I solved problem by commenting ATTR_SPEED variable in AVAILABLE_ATTRIBUTES_AIRHUMIDIFIER_CA

**Comment by syssi** [comment] 2020-10-18 21:11
This should be fixed. The property is called "raw_speed" instead of "speed" now AFAIK.

**Closed by syssi** 2020-10-18 21:11 UTC
