### ISSUE TITLE
Device nwt.derh.312en

### ISSUE THREAD

**Issue by weekendjoy** [syssi/xiaomi_airpurifier#60] opened 2020-05-15 04:02 UTC
Can you write a custom component for nwt.derh.312en device for Home Assisstant ?
It differs only in capacity and is almost the same as nwt.derh.wdh318efw1 
I think you can do it

Thanks A lot

**Comment by syssi** [comment] 2020-10-18 21:07
Duplicate of #56.

**Closed by syssi** 2020-10-18 21:07 UTC
