### ISSUE TITLE
Unsupport Device: deerma.humidifier.jsqm

### ISSUE THREAD

**Issue by Mrered** [syssi/xiaomi_airpurifier#334] opened 2023-04-16 03:37 UTC
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:130
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 11:22:01 (2 occurrences)
Last logged: 11:30:36

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsqm

**Comment by syssi** [comment] 2024-08-13 19:22
This is a duplicate of #216

**Closed by syssi** 2024-08-13 19:22 UTC
