### ISSUE TITLE
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq4

### ISSUE THREAD

**Issue by echupin** [syssi/xiaomi_airpurifier#298] opened 2022-08-31 07:30 UTC
"Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq4"

This is an error when I don't specify the model in the configuration.
Model "deerma.humidifier.jsq4" cannot be specified.
If I specify the model "deerma.humidifier.jsq", the humidifier is not available in HA.

**Comment by baradetsky** [comment] 2022-10-20 16:24
I also need this integration

**Comment by SandDeath** [comment] 2022-10-27 10:14
join the request to add

**Comment by jejunpark** [comment] 2022-11-23 12:05
I also need this integration

**Comment by Grawl** [comment] 2024-04-21 07:26
https://github.com/syssi/xiaomi_airpurifier/issues/109

**Comment by syssi** [comment] 2024-08-13 19:28
This is a duplicate of #109.

**Closed by syssi** 2024-08-13 19:28 UTC
