### ISSUE TITLE
Home Assistant 2022.9.0 still not work with Xiaomi Air Purifier 4, anyone can help?

### ISSUE THREAD

**Issue by dodo143** [syssi/xiaomi_airpurifier#299] opened 2022-09-08 14:55 UTC
2022-09-08 21:48:03.350 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.airp.mb5a

**Comment by Som83** [comment] 2022-09-11 14:55
Same for me.

**Comment by syssi** [comment] 2023-03-16 10:49
Duplicate of #301.

**Closed by syssi** 2023-03-16 10:49 UTC
