### ISSUE TITLE
Xiaomi Smart Air Purifier 4: Unsupported device

### ISSUE THREAD

**Issue by greggcsoft** [syssi/xiaomi_airpurifier#354] opened 2023-12-14 09:48 UTC
Core: 2023.12.2
Supervisor: 2023.11.6
Operating System: 11.2
Frontend: 20231208.2

2023-12-14 10:33:41.446 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.airp.mb5a

**Comment by janrg** [comment] 2023-12-20 14:51
Getting the exact same error. @syssi Is the log asking to submit issues here still current? It looks like thre haven't been any commits in this repo in half a year but https://github.com/home-assistant/core/tree/dev/homeassistant/components/xiaomi_miio was last updated two days ago.

**Comment by ealkalai** [comment] 2024-01-05 04:05
related issue #336

**Comment by syssi** [comment] 2024-08-13 19:16
Duplicate of #301

**Closed by syssi** 2024-08-13 19:16 UTC
