### ISSUE TITLE
deerma.humidifier.jsq2g

### ISSUE THREAD

**Issue by alferius** [syssi/xiaomi_airpurifier#358] opened 2024-01-04 17:06 UTC
I did it according to the instructions. There are no errors. The device does not appear in added objects. How to add to supported devices?

**Comment by neoclubber** [comment] 2024-01-20 13:22
Same. There's logs (error level)
`Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2g`

**Comment by Moony83** [comment] 2024-01-24 14:39
Same Issue, same Error:
`Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:161
Integration: Xiaomi Miio (documentation, issues)
First occurred: 15:33:54 (2 occurrences)
Last logged: 15:34:31

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w`

The Device is a "Xiaomi Smart Humidifier 2" in the EU Version.

**Comment by syssi** [comment] 2024-08-13 19:14
Duplicate of #306

**Closed by syssi** 2024-08-13 19:14 UTC
