### ISSUE TITLE
Add deerma.humidifier.jsqm support

### ISSUE THREAD

**Issue by nesoroka** [syssi/xiaomi_airpurifier#250] opened 2022-02-09 12:26 UTC
deerma.humidifier.jsqm

**Comment by soulcola** [comment] 2022-02-14 02:30
+1

**Comment by feel2006** [comment] 2022-03-04 17:51
+1

**Comment by Anonym-tsk** [comment] 2022-03-04 18:01
Duplicate #216

**Comment by ali0625** [comment] 2022-05-14 08:55
+1

**Comment by biobomb** [comment] 2022-10-01 11:21
+1

**Comment by SadCOW** [comment] 2022-10-26 22:07
+1

**Comment by syssi** [comment] 2024-08-13 19:21
This is a duplicate of #216.

**Closed by syssi** 2024-08-13 19:21 UTC
Labels: new-device
