### ISSUE TITLE
Roborock vacuum was working, now "isn't supported"?

### ISSUE THREAD

**Issue by dzazzo** [syssi/xiaomi_airpurifier#220] opened 2021-11-01 15:40 UTC
I don't really understand - this was working just fine, and now isn't.  Please add support for roborock.vacuum.a08.  Thanks.

**Comment by matata86** [comment] 2021-11-03 21:03
same problem after update to 2021.11

**Comment by xuefer** [comment] 2021-11-03 21:15
same goes with roborock.vacuum.t6

#222 is duplicate of this issue

**Comment by syssi** [comment] 2021-11-05 05:05
Please update to 2021.11.1. This should fix the issue.

**Closed by syssi** 2021-11-05 05:05 UTC
