### ISSUE TITLE
Help with MJJSQ04DY 

### ISSUE THREAD

**Issue by areyoufserious** [syssi/xiaomi_airpurifier#151] opened 2021-02-24 11:20 UTC
I'm owner of MJJSQ04DY. How can i help?

**Comment by elfim-lama** [comment] 2021-03-14 03:47
Did you manage to connect it? If so, what should be specified in the config?

**Comment by elfim-lama** [comment] 2021-03-14 04:43
> I'm owner of MJJSQ04DY. How can i help?
Help to connect?

**Comment by syssi** [comment] 2021-04-10 13:08
Anybody here to provide some testing to get this device supported?

**Comment by syssi** [comment] 2021-04-10 13:09
Duplicate of #158.

**Closed by syssi** 2021-04-10 13:09 UTC
