### ISSUE TITLE
Request Xiaomi dmaker.fan.1c fan support

### ISSUE THREAD

**Issue by johnjoemorgan** [syssi/xiaomi_airpurifier#168] opened 2021-04-11 07:49 UTC
Request Xiaomi dmaker.fan.1c fan support

Trying to upgrade from yaml config to integration the dmaker.fan.1c device is not recognized.

From the Xiaomi token scrape the details are:

   NAME:     Aunt Fanny
   ID:       240451664
   IP:       192.168.0.ccc
   TOKEN:    8254xxxxxxxxxxxxxxxxxx65e2
   MODEL:    dmaker.fan.1c

Existing, working yaml is:

  - platform: xiaomi_miio_fan
    name: 'Aunty Fanny'
    host: 192.168.0.cc
    token: 8254xxxxxxxxxxxxxxxx65e2

**Comment by syssi** [comment] 2021-04-11 07:53
The device isn't supported right now. You could track track the progress at these pull requests:

https://github.com/syssi/xiaomi_airpurifier/pull/166
https://github.com/rytilahti/python-miio/pull/1012

**Comment by matteos1** [comment] 2021-04-27 10:09
this component not work [](https://github.com/damianpasek/xiaomi_fan/tree/develop/custom_components/xiaomi_miio_fan)

**Comment by syssi** [comment] 2021-05-06 20:33
Duplicate of https://github.com/syssi/xiaomi_airpurifier/issues/68

**Closed by syssi** 2021-05-06 20:33 UTC
