### ISSUE TITLE
Please add support to zhimi.airp.mb5a

### ISSUE THREAD

**Issue by uhwf91p** [syssi/xiaomi_airpurifier#336] opened 2023-04-22 13:52 UTC
I've tried to connect my new air purifier to homeassistant and got the following error:
ERROR (MainThread) [homeassistant.components.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.airp.mb5a
Could you please add support for it?

**Comment by cerritus55** [comment] 2023-07-29 09:02
I have the same problem

> 2023-07-29 10:43:31.334 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.airp.mb5a
> 
Any chance this getting support?

**Comment by VanQz** [comment] 2023-07-31 13:46
Have this issue too. Please add support for this thanks!

**Comment by wlucha** [comment] 2023-08-09 20:37
Same issue here, please add support

**Comment by phbasler** [comment] 2023-08-09 20:42
Because I didn't want to wait:
I had great success with the python api of the main branch https://github.com/rytilahti/python-miio.git . Using the device factory it was easy writing up a python script for the stuff I wanted to control.
To connect the script to HA you can use MQTT

**Comment by cerritus55** [comment] 2023-08-10 16:14
I also It also didn’t want to wait. I had a great success with an HACS repo, works for me just fine.
https://github.com/al-one/hass-xiaomi-miot

**Comment by p2bauer** [comment] 2023-08-29 22:52
Looks like I'll also go for the HACS repo above that @cerritus55 mentioned - but wanted to keep this issue alive since it would be great to be supported with the core integration! :-)

**Comment by MisiekG** [comment] 2024-02-13 13:25
I have the same problem, please add integration.

**Comment by syssi** [comment] 2024-08-13 19:16
Duplicate of #301

**Closed by syssi** 2024-08-13 19:16 UTC
