### ISSUE TITLE
Add zhimi.airp.mb5a support

### ISSUE THREAD

**Issue by MuzzaGuzzaBuzza** [syssi/xiaomi_airpurifier#363] opened 2024-03-31 01:34 UTC
Greetings

Trying to add Xiaomi Air Purifier 4, but it looks like this particular model/edition isn't yet supported: zhimi.airp.mb5a. Two other Air Purifier 4s I have are zhimi.airp.mb5 and they have integrated perfectly into HA.

Any chance of an update to include this model?

Many thanks

**Comment by OB1KOB** [comment] 2024-04-10 10:55
I think here the same problem Xiaomi Air Purifier 4

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.airp.mb5a

**Comment by filipkotoucek** [comment] 2024-06-13 20:19
+1 same here. I have HASS in docker lscr.io/linuxserver/homeassistant latest 379fd0081054. Would this model be supprted anytime?

**Comment by syssi** [comment] 2024-08-13 19:16
Duplicate of #301

**Closed by syssi** 2024-08-13 19:16 UTC
Labels: new-device
