### ISSUE TITLE
Please add support to deerma.humidifier.jsq2g

### ISSUE THREAD

**Issue by wngweiping** [syssi/xiaomi_airpurifier#339] opened 2023-05-30 13:58 UTC
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:130
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 21:44:17 (2 occurrences)
Last logged: 21:52:40

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2g

**Comment by AlexzeyK** [comment] 2023-06-05 09:02
Hi guys.
I also bought this device. I also received an unsupported device.

Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:130
Integration: Xiaomi Miio (documentation, issues)
First occurred: 4 червня 2023 р. о 22:34:49 (1 occurrences)
Last logged: 4 червня 2023 р. о 22:34:49

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2g

It is now being actively sold. Please add support for this device.

**Comment by adriannowak** [comment] 2023-07-02 19:28
Up with `deerma.humidifier.jsq2w`

**Comment by LeChat109** [comment] 2023-07-15 00:02
up

**Comment by leandrofranca** [comment] 2023-09-28 04:52
Up

**Comment by nilsi** [comment] 2023-10-04 14:20
Same here, would also love if this was supported!

**Comment by AlexzeyK** [comment] 2023-10-04 15:32
I already have 4 such devices. 
Now I use HACS. But we really need direct support from HA!

**Comment by DmitryL0** [comment] 2023-10-10 22:20
Up

**Comment by wolfich** [comment] 2023-10-29 21:05
up!

**Comment by Hedin9000** [comment] 2023-11-06 10:28
deerma.humidifier.jsq2g
Xiaomi Smart Humidifier 2 (MJJSQ05DY)

**Comment by alexandersaulenko** [comment] 2023-12-05 18:56
up!

**Comment by DmitryL0** [comment] 2023-12-09 15:25
Up

**Comment by mrmuro** [comment] 2024-01-12 14:53
Up

**Comment by fralloger** [comment] 2024-01-14 15:53
up!

**Comment by RhavoX** [comment] 2024-02-03 19:26
Up

**Comment by QAstron** [comment] 2024-03-04 14:34
Up

**Comment by grandead** [comment] 2024-04-15 18:07
Up

**Comment by Zalmat** [comment] 2024-04-30 11:15
Up

**Comment by cydwg** [comment] 2024-06-25 15:20
Up, also have the same issue

**Comment by syssi** [comment] 2024-08-13 19:15
Duplicate of #306

**Closed by syssi** 2024-08-13 19:15 UTC
